version: "3.8"

networks:
  net:
    name: net
    driver: bridge

volumes:
  mariadbV:
    driver: local
    name: mariadbV
    driver_opts:
      type: none
      o: bind
      device: /home/zasabri/data/mariadb
  wordpressV:
    driver: local
    name: wordpressV
    driver_opts:
      type: none
      o: bind
      device: /home/zasabri/data/wordpress

services:
  nginx:
    container_name: nginx
    image: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpressV:/var/www/html
    networks:
      - net
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpressV:/var/www/html
    networks:
      - net
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb
    build: requirements/mariadb
    volumes:
      - mariadbV:/var/lib/mysql
    networks:
      - net
    restart: always