#vesrion: "3.8"
#services:
#  mariadb:
#  wordpress:
#  nginx:
version: "3.8"
services:
  website:
    image: nginx
    ports:
      - "7777:80"
    volumes:
      - store:/root
    restart: always
volumes:
  store: