version: "3.8"
services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    networks:
      - net
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/html/
    depends_on:
      - wordpress
  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    container_name: wordpress
    networks:
      - net
    volumes:
      - wp-data:/timssah/
    depends_on:
      - mariadb
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    networks:
      - net
    volumes:
      - mariadb:/root
    restart: always
networks:
  net:
    driver: bridge
volumes:
  wp-data:
    driver: local
    driver_opts:
      device: /home/zasabri/data/
      type: none
      o: bind
  mariadb:
    driver: local
    driver_opts:
      device: /home/zasabri/data/
      type: none
      o: bind