version: "3.8"
services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - zakNet
    volumes:
      - mariadb:/home/zasabri/data
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    networks:
      - zakNet
    volumes:
      - wordpress:/var/www/html/
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "4444:80"
    networks:
      - zakNet
    volumes:
      - wordpress:/var/www/html/
volumes:
  wordpress:
  mariadb:
networks:
  zakNet: