FROM    adminer
# RUN     apt update -y
# RUN     apt install mariadb-server -y
# RUN     apt install adminer -y
# COPY    ./tools/run.sh /bin
# COPY    ./conf/000-default.conf /etc/apache2/sites-available
# RUN     chmod 777 /bin/run.sh
# CMD ["run.sh"]